"""Fix user password_hash size to 256

Revision ID: 9297e0371969
Revises: 
Create Date: 2025-11-11 13:13:45.484389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9297e0371969'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        op.alter_column(
            'user_data', # <- Verify this is your user table name!
            'password_hash',
            existing_type=sa.VARCHAR(128),
            type_=sa.String(256),
            existing_nullable=False,
            postgresql_using='password_hash::varchar(256)'
        )
        # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user_data', # <- Verify this is your user table name!
        'password_hash',
        existing_type=sa.String(256),
        type_=sa.VARCHAR(128),
        existing_nullable=False,
        postgresql_using='password_hash::varchar(128)'
    )
# ### end Alembic commands ###
