name: Python App

on:
  push:
    branches: [ main ]  # run workflow when you push to main branch
  pull_request:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}  # GitHub Secret
        run: python my_script.py
